service: lambda-environment

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage, 'qa'}
  environment: ${file(./config/env.${self:provider.stage}.json)}
  iam:
    role:
      statements: ${file(./config/serverless/db.iam.role.yml)}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

resources:
  Resources: ${file(./config/serverless/resources/dynamo.commits.table.yml)}

functions:
  commit-message-scheduler:
    handler: src/index.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: Get commit messages each minute
          enabled: ${self:custom.enabled}
